version: '3'
services:
  app:
    image: ggmartinez/laravel:9-php7-Xdebug
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./:/app 
    depends_on:
      - "mysql"
    environment:
      - XDEBUG_CONFIG=log=/dev/null
  mysql:
    image: mysql:5.7
    restart: unless-stopped 
    tty: true 
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=laravel
